### ISSUE TITLE
Provide a 'InvalidCredential' exception

### ISSUE THREAD

**Issue by ZeHiro** [bankscrap/bankscrap#47]
In my way to integrate bankscrap to Kresus (https://kresus.org), it would be really useful that bankscrap provides a standardized exception to say the credentials are invalid (and of course used in the modules). As Kresus is a webapp, with the aim of warning the user he maid a mistake. Currently, when I try to use two different modules with bad credentials i get this : 
ING : 
```
/home/tonio/.gem/ruby/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch': 400 => Net::HTTPBadRequest for https://ing.ingdirect.es/genoma_login/rest/session -- unhandled response (Mechanize::ResponseCodeError)
	from /home/tonio/.gem/ruby/gems/mechanize-2.7.5/lib/mechanize.rb:562:in `request_with_entity'
	from /home/tonio/.gem/ruby/gems/mechanize-2.7.5/lib/mechanize.rb:511:in `post'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/bank.rb:63:in `post'
	from /home/tonio/.gem/ruby/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:108:in `request_pinpad_positions'
	from /home/tonio/.gem/ruby/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:97:in `login'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/bank.rb:29:in `initialize'
	from /home/tonio/.gem/ruby/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:24:in `initialize'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/cli.rb:80:in `new'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/cli.rb:80:in `initialize_client_for'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/cli.rb:22:in `balance'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/bin/bankscrap:5:in `<top (required)>'
	from /home/tonio/bin/bankscrap:22:in `load'
	from /home/tonio/bin/bankscrap:22:in `<main>'
```
and BBVA
```
/usr/share/ruby/json/common.rb:155:in `parse': 757: unexpected token at '<logon/> (JSON::ParserError)
'
	from /usr/share/ruby/json/common.rb:155:in `parse'
	from /home/tonio/.gem/ruby/gems/bankscrap-bbva-2.0.1/lib/bankscrap/bbva/bank.rb:49:in `fetch_accounts'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/bank.rb:30:in `initialize'
	from /home/tonio/.gem/ruby/gems/bankscrap-bbva-2.0.1/lib/bankscrap/bbva/bank.rb:20:in `initialize'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/cli.rb:80:in `new'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/cli.rb:80:in `initialize_client_for'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/lib/bankscrap/cli.rb:22:in `balance'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/tonio/.gem/ruby/gems/bankscrap-2.0.3/bin/bankscrap:5:in `<top (required)>'
	from /home/tonio/bin/bankscrap:22:in `load'
	from /home/tonio/bin/bankscrap:22:in `<main>'
```
```

**Comment by javiercr** [comment]
This totally makes sense. Thank your for the feedback! 

@raulmarcosl we should make sure adapters throw proper exceptions (probably defined in the core library). What do you think?

**Comment by raulmarcosl** [comment]
Totally agree! We can modify the adapter generator to expect the new adapters throw those exceptions, and modify the old ones.

Thanks for the suggestion @ZeHiro.

**Comment by albfan** [comment]
Sounds like an easy task to implement. @ZeHiro do you have any WIP for this? 

I think you can add a wip branch on https://github.com/bnjbvr/kresus (wip/bankscrap for example?)

To see how you use bankscrap inside kresus and fix whatever needs to be fixed

**Comment by ZeHiro** [comment]
@albfan first we need to enhance some things on kresus' sides. Like making the server far more independant from Weboob, which is our current backend (for French banks). Nothing hard, mostly code revamp, I had started smthg, I'll dive into it in August.

**Comment by albfan** [comment]
Great. Feel free to start an non working skeleton for that at any time. Dive into new codebases is always the tedious part
