### ISSUE TITLE
Scraping ing for balance returns 400

### ISSUE THREAD

**Issue by qdii** [bankscrap/bankscrap#54]
I'm running bankscrap-2.0.5 and bankscrap-ing-2.0.3.

```
$ bankscrap balance ING --credentials=dni:[EDITED] password:[EDITED] birthday:[EDITED]
/home/qdii/.gem/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch': 400 => Net::HTTPBadRequest for https://ing.ingdirect.es/genoma_login/rest/session -- unhandled response (Mechanize::ResponseCodeError)
	from /home/qdii/.gem/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:562:in `request_with_entity'
	from /home/qdii/.gem/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:511:in `post'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/bank.rb:63:in `post'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:108:in `request_pinpad_positions'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:97:in `login'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/bank.rb:29:in `initialize'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:24:in `initialize'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/cli.rb:80:in `new'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/cli.rb:80:in `initialize_client_for'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/cli.rb:22:in `balance'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/bin/bankscrap:5:in `<main>'
```

I'm not familiar with ruby but I'll try to do my best to help.

**Comment by raulmarcosl** [comment]
Hi, @qdii!

I have tried on my machine, with those versions, and it's working for me.

Which birthday format are you using? It should be as `birthday:01/01/1970`. It's the only problem that I can think of, apart from having problems logging in the web too.

**Comment by qdii** [comment]
I tried both birthday 14/01/1970 and 01/14/1970 but neither of them are working: I get the same error regardless. Is there a way I could patch the code to dump the retrieved page and see the error?

**Comment by javiercr** [comment]
@qdii is your ING account from Spain or somewhere else? I am not sure if the API endpoint is valid for all countries where ING operates.

Regarding getting more info about the error you can try passing the `--debug` flag to the CLI:

`$ bankscrap balance ING --credentials=dni:[EDITED] password:[EDITED] birthday:[EDITED] --debug`

**Comment by qdii** [comment]
Yep, ING Direct de España :)

```
$ /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/bin/bankscrap balance ING --debug --credentials=dni:[EDITED] password:[EDITED] birthday:[EDITED]                                                                                                                                                                        
D, [2017-08-11T20:44:59.225946 #29904] DEBUG -- : query: "{\"loginDocument\":{\"documentType\":0,\"document\":\"[EDITED]\"},\"birthday\":\"[EDITED]\",\"companyDocument\":null,\"device\":\"desktop\"}"
I, [2017-08-11T20:44:59.226244 #29904]  INFO -- : Net::HTTP::Post: /genoma_login/rest/session
D, [2017-08-11T20:44:59.226272 #29904] DEBUG -- : request-header: accept-encoding => gzip,deflate,identity
D, [2017-08-11T20:44:59.226299 #29904] DEBUG -- : request-header: accept => application/json, text/javascript, */*; q=0.01
D, [2017-08-11T20:44:59.226313 #29904] DEBUG -- : request-header: user-agent => Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19
D, [2017-08-11T20:44:59.226326 #29904] DEBUG -- : request-header: accept-charset => ISO-8859-1,utf-8;q=0.7,*;q=0.7
D, [2017-08-11T20:44:59.226337 #29904] DEBUG -- : request-header: accept-language => en-us,en;q=0.5
D, [2017-08-11T20:44:59.226348 #29904] DEBUG -- : request-header: host => ing.ingdirect.es
D, [2017-08-11T20:44:59.226360 #29904] DEBUG -- : request-header: content-type => application/json; charset=utf-8
D, [2017-08-11T20:44:59.226371 #29904] DEBUG -- : request-header: content-length => 125
I, [2017-08-11T20:44:59.565816 #29904]  INFO -- : status: Net::HTTPBadRequest 1.1 400 Bad Request
D, [2017-08-11T20:44:59.566049 #29904] DEBUG -- : response-header: date => Fri, 11 Aug 2017 19:44:59 GMT
D, [2017-08-11T20:44:59.566149 #29904] DEBUG -- : response-header: server => Apache
D, [2017-08-11T20:44:59.566242 #29904] DEBUG -- : response-header: strict-transport-security => max-age=631138519; includeSubDomains
D, [2017-08-11T20:44:59.566313 #29904] DEBUG -- : response-header: pragma => no-cache, no-cache
D, [2017-08-11T20:44:59.566376 #29904] DEBUG -- : response-header: expires => Thu, 01 Jan 1970 00:00:00 GMT, Thu, 01 Jan 1970 00:00:00 GMT
D, [2017-08-11T20:44:59.566439 #29904] DEBUG -- : response-header: cache-control => no-cache, no-store, no-cache, no-store, max-age=0
D, [2017-08-11T20:44:59.566500 #29904] DEBUG -- : response-header: content-language => en-US
D, [2017-08-11T20:44:59.566558 #29904] DEBUG -- : response-header: x-xss-protection => 1; mode=block
D, [2017-08-11T20:44:59.566629 #29904] DEBUG -- : response-header: x-content-type-options => nosniff
D, [2017-08-11T20:44:59.566707 #29904] DEBUG -- : response-header: set-cookie => genoma-session-id=661718b3-51fd-4f35-85f5-2ca8147305df; Path=/genoma_login/; Secure; HttpOnly
D, [2017-08-11T20:44:59.566786 #29904] DEBUG -- : response-header: vary => User-Agent,Accept-Encoding
D, [2017-08-11T20:44:59.566867 #29904] DEBUG -- : response-header: content-encoding => gzip
D, [2017-08-11T20:44:59.566950 #29904] DEBUG -- : response-header: connection => close
D, [2017-08-11T20:44:59.567031 #29904] DEBUG -- : response-header: transfer-encoding => chunked
D, [2017-08-11T20:44:59.567108 #29904] DEBUG -- : response-header: content-type => application/json;charset=UTF-8
D, [2017-08-11T20:44:59.567481 #29904] DEBUG -- : Read 182 bytes (182 total)
D, [2017-08-11T20:44:59.567709 #29904] DEBUG -- : Read 10 bytes (192 total)
D, [2017-08-11T20:44:59.568202 #29904] DEBUG -- : gzip response
D, [2017-08-11T20:44:59.575260 #29904] DEBUG -- : saved cookie: genoma-session-id=661718b3-51fd-4f35-85f5-2ca8147305df
/home/qdii/.gem/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch': 400 => Net::HTTPBadRequest for https://ing.ingdirect.es/genoma_login/rest/session -- unhandled response (Mechanize::ResponseCodeError)
	from /home/qdii/.gem/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:562:in `request_with_entity'
	from /home/qdii/.gem/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:511:in `post'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/bank.rb:63:in `post'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:108:in `request_pinpad_positions'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:97:in `login'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/bank.rb:29:in `initialize'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-ing-2.0.3/lib/bankscrap/ing/bank.rb:24:in `initialize'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/cli.rb:80:in `new'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/cli.rb:80:in `initialize_client_for'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/cli.rb:22:in `balance'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/qdii/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/qdii/.gem/ruby/2.4.0/gems/bankscrap-2.0.5/bin/bankscrap:5:in `<main>'
```

**Comment by javiercr** [comment]
@raulmarcosl could you take a look? 🙏

**Comment by qdii** [comment]
I'm not really familiar with perl, but I guess you are just sending a few requests to an API endpoint. Maybe you could give me an equivalent of the request in bash or python to see if that works?
