### ISSUE TITLE
Errors for Openbank

### ISSUE THREAD

**Issue by kahironimashte** [bankscrap/bankscrap#60]
Hi when I enter the command `bankscrap balance Openbank --credentials=(...)` i get errors like

`/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in require': cannot load such file -- bankscrap-openbank (LoadError)
` 

or

`/var/lib/gems/2.7.0/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:125:in rescue in find_bank_class_for': Invalid bank name. (ArgumentError)`

Form more details see https://github.com/bankscrap/bankscrap-openbank/issues/4

**Comment by raulmarcosl** [comment]
Hi @kahironimashte.

I don't have an Openbank account, so I can't try running Bankscrap with a valid account, but I'm not getting the same as error that you (I pasted it below).

I think your problem is that you don't have installed the openbank gem (`gem install bankscrap-openbank`). Can you try after installing it?

```
bankscrap balance Openbank --credentials=user:24242 password:2342423                                                                          1 ↵ | 2.6.3 Ruby | 10:30:57 
Traceback (most recent call last):
	19: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	18: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	17: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/bin/bankscrap:23:in `<main>'
	16: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/bin/bankscrap:23:in `load'
	15: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-2.1.1/bin/bankscrap:5:in `<top (required)>'
	14: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	13: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	12: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	10: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:24:in `balance'
	 9: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:118:in `initialize_client_for'
	 8: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:118:in `new'
	 7: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-openbank-3.0.0/lib/bankscrap/openbank/bank.rb:22:in `initialize'
	 6: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-2.1.1/lib/bankscrap/bank.rb:29:in `initialize'
	 5: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-openbank-3.0.0/lib/bankscrap/openbank/bank.rb:47:in `login'
	 4: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-openbank-3.0.0/lib/bankscrap/openbank/bank.rb:78:in `post'
	 3: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/bankscrap-2.1.1/lib/bankscrap/bank.rb:65:in `post'
	 2: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/mechanize-2.7.6/lib/mechanize.rb:511:in `post'
	 1: from /Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/mechanize-2.7.6/lib/mechanize.rb:562:in `request_with_entity'
/Users/raulmarcosl/.rvm/gems/ruby-2.6.3/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:329:in `fetch': 400 => Net::HTTPBadRequest for https://api.openbank.es/authenticationcomposite/login -- unhandled response (Mechanize::ResponseCodeError)
```

**Comment by ghost** [comment]
@raulmarcosl
